### ISSUE TITLE
Can you allow Did you know section to not be filtered?

### ISSUE THREAD

**Issue by thinkpad4** [Tetrax-10/imdb-clean-as-fuck#1]
@Tetrax-10 I like the trivia and goofs section and don't wanna have to disable your filter to see it.  Thank you very much

**Comment by Tetrax-10** [comment]
Welcome, Unfortunately, I'm unable to accommodate your request as the intention of this filter is to eliminate less important elements that are not related to Movies and TV shows.

However, you can edit this filter by copying the contents of [this file](https://raw.githubusercontent.com/Tetrax-10/imdb-clean-as-fuck/main/imdb-clean-as-fuck.txt) and pasting it into your "My filters" tab in uBlock Origin. Remove the line that reads `imdb.com##section[data-testid="DidYouKnow"]`. Ensure that you uninstall my version of the filter list (Filter list -> Custom -> IMDb Clean as F*ck).

**Comment by thinkpad4** [comment]
@Tetrax-10 I figured out a even better filter,  I just added #@#section[data-testid="DidYouKnow"] into My Filters and it overrides that part of your filter and I don't have to uninstall your filter

**Comment by Tetrax-10** [comment]
Ohh i never knew this syntax. Thx for letting me know. That would be really helpful.

**Comment by thinkpad4** [comment]
Yeah, #@# allows something that a filter list blocked `https://help.adblockplus.org/hc/en-us/articles/360062733293-How-to-write-filters#elemhide_basic`

**Comment by Rusenche** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/1863id6/made_a_filter_to_unbloat_imdb_my_first_filter_too/kb8t9vw/

**Comment by Tetrax-10** [comment]
please dont share unnecessary links here

**Comment by Rusenche** [comment]
You are right about the word "unnecessary" - the filter itself is exactly that, and hiding particularly important menus does not make it good, but - bad.

**Comment by Tetrax-10** [comment]
What's wrong with hiding elements 😂 it's my wish and am not forcing people to use this, and why you so tensed up? This filterlist is for people who don't give a fuck about stuffs that aren't movies and TV shows. If you think this filter is bad just don't use it. I can already see thousands of people installing it, and positive comments in websites so people do think it's good. Come on bro don't waste time arguing about this. This place is not for chat. I don't expect a reply.
